<main>
    <h2>Modifier la tâche</h2>
    <form action="edit.php?id=<?= htmlspecialchars($task['id']) ?>" method="post">
        <label for="name">Nom</label>
        <input type="text" name="name" id="name" value="<?= htmlspecialchars($task['name']) ?>" required>

        <label for="description">Description</label>
        <textarea id="description" name="description" rows="6" required><?= htmlspecialchars($task['description']) ?></textarea>

        <input type="checkbox" name="urgent" id="urgent" <?= $task["urgent"] ? "checked" : "" ?>>
        <label for="urgent">Urgent</label>

        <input type="checkbox" name="important" id="important" <?= $task["important"] ? "checked" : "" ?>>
        <label for="important">Important</label>

        <button type="submit">Mettre à jour</button>
    </form>
</main>
