<?php
// Démarre la session seulement si elle n'est pas déjà active
if (session_status() == PHP_SESSION_NONE) {
    session_start(); // Démarre la session uniquement si elle n'est pas déjà active
}
?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="assets/css/style.css" type="text/css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&family=Dela+Gothic+One&family=Jacquard+12&family=Piedra&family=Spicy+Rice&display=swap" rel="stylesheet">
</head>


<body>


    <header>
   
        <a href="index.php">Accueil</a>
            <?php if(!empty($_SESSION)): ?>
             <div class="left">
             <a href="userAccount.php">Mon compte</a>
             <a href="logout.php">Déconnexion</a>
             <a href="quizz.php">Jouer</a>
            </div>
            <?php else : ?>
            <div class="left">
             <a href="login.php">Connexion</a>
            <a href="register.php">Inscription</a>
            </div>
            <?php endif;?>
   
    </header>

    
    <main>
        
        <?php include "$template.phtml" ?>
        
    </main>
    
    
</body>
</html>