
  <main class="mainc">
        <section class="contact-section">
            <h1 class="h1">Connexion</h1>
            <form class="contact-form" action="#" method="POST">
                <label for="email">Identifiant</label>
                <input type="text" id="email" name="email" placeholder="Entrez votre username" required>
                <label for="password">Mot de passe</label>
                <input type="password" id="password" name="password" placeholder="Entrez votre mot de passe" required>

   
      
                <button type="submit">Envoyer</button>
            </form>
        <?php if(isset($error)): ?>
        
        <p><?= $error ?></p>
        
        <?php endif; ?>
        </section>
    </main>

