<h1>Quiz Akinator</h1>

<main class="container">
    
<div class="result">
    
    <?php if ($result): ?>
    
        <h2 class="h2">Résultat : <?= htmlspecialchars($result['name']); ?></h2>
        <p><?= htmlspecialchars($result['description']); ?></p>
        <img src="<?= htmlspecialchars($result['visuel']); ?>" alt="Image du résultat">
        
    <?php elseif ($currentQuestion): ?>
      
        <p class="p"><?= htmlspecialchars($currentQuestion['name']); ?></p>
        <form method="POST" action="">
            <button type="submit" name="answer" value="Oui" class="btn-oui">Oui</button>
            <br>
            <button type="submit" name="answer" value="Non" class="btn-non">Non</button>
        </form>
 <a href="quizz.php?question_id=1" class="delete" >Recommencer le quiz</a>

    <?php else: ?>
        <p>Aucune question disponible.</p>
    <?php endif; ?>
    
</div>
</main>