<h1 class="h1">Quiz Akinator</h1>

<main class="container">
    
<div class="result">
    
     <?php if ($currentQuestion): ?>
        <div class="p">
            <p class="question-text"><?= htmlspecialchars($currentQuestion['name']); ?></p>
            
            <form method="POST" action="">
                <button type="submit" name="answer" value="Oui" class="btn-oui">Oui</button>
                <br>
                <button type="submit" name="answer" value="Non" class="btn-non">Non</button>
            </form>
        </div>
    <?php else: ?>
        <p>Aucune question disponible.</p>
    <?php endif; ?>
    
   
    <a href="quizz.php?question_id=1" class="delete">Recommencer le quiz</a>

    
</div>
</main>