 <main class="mainc">
        <section class="contact-section">
            <h1 class="h1">Inscription</h1>
            <form class="contact-form" action="#" method="POST">
                 <label for="username">Username</label>
                <input type="text" id="username" name="username" placeholder="Entrez votre username" required>
                <label for="email">Email</label>
                <input type="text" id="email" name="email" placeholder="Entrez votre email" required>
                <label for="password">Mot de passe</label>
                <input type="password" id="password" name="password" placeholder="Entrez votre mot de passe" required>

                <button type="submit">Créer un compte</button>
            </form>
             <?php if(isset($error)): ?>
        
        <p><?= $error ?></p>
        
        <?php endif; ?>
        </section>
    </main>

