<main class="mainc">
    <h1>Historique des parties</h1>
    
    <h2>Changer mon mot de passe</h2>
    <p>Votre mot de passe doit contenir entre 8 et 16 lettres, avec au moins une majuscule, 1 chiffre et 1 caractère spécial</p>
    <form method="POST" action="">
         <label for="password">Mot de passe actuel</label>
         <input type="password" id="password" name="password" placeholder="Entrez votre mot de passe actuel" required>
         <label for="password">Nouveau mot de passe</label>
         <input type="password" id="password" name="password" placeholder="Entrez votre nouveau mot de passe" required>

         <p>Êtes-vous sûr de vouloir supprimer votre compte ?</p>
         <button type="submit" name="delete_account">Supprimer mon compte</button>
    </form>
</main>
    


