<main class="mainc">
<h1 class="h1">Bienvenue <?= htmlspecialchars($_SESSION['username']) ?> !</h1>
    <h1 class="h11">Historique des parties</h1>
    <?php if(!empty($gameData)): ?>
       <?php foreach($gameData as $data): ?>
           <div class="flex-resultat">
               <p>Le <?= date('d/m/Y', strtotime($data['date'])); ?></p>
               <p><?= $data['result_name'] ?></p>
           </div>
         <?php endforeach; ?>
         <a class="delete" href="deleteResult.php">Supprimez l'historique</a>
   <?php else: ?>
   <p class="p">Aucune partie jouée !</p>
   <?php endif; ?>
   
   <br>
   
<h2>Changer mon mot de passe</h2>
<p>Votre mot de passe doit contenir entre 8 et 16 lettres, avec au moins une majuscule, 1 chiffre et 1 caractère spécial.</p>
    
<form class="contact-form" action="#" method="POST">
    
    <label for="password">Mot de passe actuel</label>
    <input type="password" id="password" name="current_password" placeholder="Entrez votre mot de passe actuel" required>
         
    <label for="password">Nouveau mot de passe</label>
    <input type="password" id="password" name="new_password" placeholder="Entrez votre nouveau mot de passe" required>
         
    <button type="submit">Modifier le mot de passe</button>
    <br>
</form>
            
<?php if (isset($error)): ?>
    <p><?= $error ?></p>
<?php endif; ?>

            
<form method="POST" action="">
<p>Êtes-vous sûr de vouloir supprimer votre compte ?</p>
<button type="submit" name="delete_account">Supprimer mon compte</button>
</form>

</main>
    


